### ISSUE TITLE
%ping% is showing a constant of "1 ms" on 1.20.6

### ISSUE THREAD

**Issue by k-jiang** [joserodpt/RealScoreboard#73]
Tested with RealScoreboard 1.4.2, and Spigot 1.20.6. Seems it is exactly the same behavior of #32.

**Comment by joserodpt** [comment]
Hi there! Thanks for the report. Please test this .jar file and give me some feedback, thanks!

[RealScoreboard.jar.zip](https://github.com/user-attachments/files/15945102/RealScoreboard.jar.zip)

**Comment by k-jiang** [comment]
> Hi there! Thanks for the report. Please test this .jar file and give me some feedback, thanks!
> 
> [RealScoreboard.jar.zip](https://github.com/user-attachments/files/15945102/RealScoreboard.jar.zip)

`%ping%` is working. But RGB color code is broken now:
<img width="269" alt="image" src="https://github.com/joserodpt/RealScoreboard/assets/6910542/7c7fab96-8443-46ad-b78c-b09b32de5d31">
```yaml
Scoreboards:
    Title:
    - '&#7FFF00随便MC-生存服'
    Lines:
    - '&#87CEFA&l&m*=--=--=--=--=--=*'
    - '&#00FF7F   延迟&#00FF7F&l&f    %ping%'
```
